version: '3.9'

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - '4000:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=ghtk@123
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
  redis-master:
    image: bitnami/redis:7.2.1
    ports:
      - '6379:6379'
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD: ghtk@123
  redis-slave:
    image: bitnami/redis:7.2.1
    depends_on:
      - redis-master
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_PASSWORD: ghtk@123
      REDIS_PASSWORD: ghtk@123
  redis-sentinel:
    image: bitnami/redis-sentinel:7.2.1
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - '26379-26381:26379'
    environment:
      REDIS_MASTER_SET: redis-cluster
      REDIS_MASTER_HOST: localhost
      REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS: 10000
      REDIS_MASTER_PASSWORD: ghtk@123
#  elasticsearch:
#    image: elasticsearch:8.10.2
#    container_name: elasticsearch
#    ports:
#      - '9200:9200'
#    environment:
#      discovery.type: single-node
#      xpack.security.enabled: "false"
#  kafka-1:
#    image: confluentinc/cp-kafka
#    restart: always
#    ports:
#      - '9092:9092'
#    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
#      KAFKA_LISTENERS: 'INTERNAL://kafka-1:29092,CONTROLLER://kafka-1:29093,EXTERNAL://0.0.0.0:9092'
#      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092'
#      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
#      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093'
#      KAFKA_PROCESS_ROLES: 'broker,controller'
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
#      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
#      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
#  kafka-2:
#    image: confluentinc/cp-kafka
#    restart: always
#    ports:
#      - '9093:9093'
#    environment:
#      KAFKA_NODE_ID: 2
#      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
#      KAFKA_LISTENERS: 'INTERNAL://kafka-2:29092,CONTROLLER://kafka-2:29093,EXTERNAL://0.0.0.0:9093'
#      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-2:29092,EXTERNAL://localhost:9093'
#      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
#      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093'
#      KAFKA_PROCESS_ROLES: 'broker,controller'
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
#      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
#      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
#  kafka-ui:
#    image: provectuslabs/kafka-ui:v0.7.1
#    restart: always
#    depends_on:
#      - kafka-1
#      - kafka-2
#    ports:
#      - '8888:8080'
#    environment:
#      - DYNAMIC_CONFIG_ENABLED=true
#    volumes:
#      - ./kafka/ui/config.yaml:/etc/kafkaui/dynamic_config.yaml